### ISSUE TITLE
BUG CANT INSTALL NPM INSTALL 

### ISSUE THREAD

**Issue by pengengantibaju** [synzen/MonitoRSS-Clone#33]
![Screenshot_20220515-014119032](https://user-images.githubusercontent.com/92777707/168444510-c74af2e8-c593-4b0a-b4a9-004920125b4f.jpg)

**Comment by synzen** [comment]
The npm install had succeeded - they are just optional dependencies that requires them to be compiled using build tools since they are written in C++, and if your system doesn't have those tools, then the build will fail.

But you can see there `SKIPPING OPTIONAL DEPENDENCY` and at the end, `added 406 packages`
